### PR TITLE
update .gitlab ci

### PR DESCRIPTION
**Pull request by kevinhkhuynh**
Update .gitlab-ci yaml file for rom branch

### CODE REVIEW

**Comment by kevinhkhuynh** [comment]
LGTM

**Comment by kevinhkhuynh** [comment]
LGTM

**Comment by kevinhkhuynh** [comment]
I'll merge this after 1 approval since I don't think anyone needs to review this.

**Comment by kevinhkhuynh** [comment]
A problem with Gitlab is that if the YAML file is not in the main directory, then Gitlab can not find the YAML file to run the job. We will have to put the YAML file in the main directory if we want to continue to use Gitlab.

**Review by dylan-copeland — APPROVED** [review]

**Pull request merged**
