### PR TITLE
gitlab Setup

### PR DESCRIPTION
**Pull request by kevinhkhuynh**
Setting up a simple Gitlab CI/CD for rom-dev. This runs the regression tests on a quartz shell when 'LGTM' is commented in a pull request. It doesn't seem much easier than running the test script manually, but it can be useful in the future. I tested it and the CI pipeline should pass, but it won't pass right now because I made changes to the makefile and the rom-dev branch doesn't have this change. But once it's merged, 'LGTM' can be used. If a single test out of 32 fails, the pipeline will appear as failed.

### CODE REVIEW

**Comment by chldkdtn** [comment]
@kevinhkhuynh  the manual regression test fails for this PR. Are you aware of it?

**Comment by kevinhkhuynh** [comment]
> @kevinhkhuynh the manual regression test fails for this PR. Are you aware of it?

Yes. Since the makefile has changed, the regression test will fail because the master branch can't build correctly without passing in the correct parameters in the regression test script. It should work when the makefile changes have merged. I should've divided it into two pull requests, but I felt this time, the changes were so minor I could put it into one.

**Comment by chldkdtn** [comment]
> > @kevinhkhuynh the manual regression test fails for this PR. Are you aware of it?
> 
> Yes. Since the makefile has changed, the regression test will fail because the master branch can't build correctly without passing in the correct parameters in the regression test script. It should work when the makefile changes have merged. I should've divided it into two pull requests, but I felt this time, the changes were so minor I could put it into one.

sounds good to me. @dylan-copeland , are you okay with this change?

**Review by chldkdtn — APPROVED** [review]

**Comment by dylan-copeland** [comment]
I am not planning to review this PR, so please feel free to merge.

**Pull request merged**
