### PR TITLE
Remove redundant sampling when time windows are finalized

### PR DESCRIPTION
**Pull request by siuwuncheung**
This PR removes the redundant sample in the `ROM_Sampler::Finalize` call of the time windows. The same snapshot vector has been sampled in `ROM_Sampler::SampleSolution` call.

### CODE REVIEW

**Comment by dylan-copeland** [comment]
@siuwuncheung This PR looks good to me, and the only thing left to verify is that it doesn't break anything. The regression tests are failing, which makes sense as the basis sizes are changed. Can you comment on whether you verified the differences in the tests are minor (e.g. just different basis sizes)? For example, you may be able to just comment out `check_fail` after `basisComparator` is called in `runRegressionTests.sh`, to eliminate failures due to basis differences. There could still be other small differences that need to be checked manually (e.g. compare ROM online solution errors that may be slightly different). If you describe your verification, it can help the reviewers.

**Comment by chldkdtn** [comment]
@siuwuncheung , please resolve the conflict introduced due to the recent merge of PR #77 to the rom-dev.

**Comment by siuwuncheung** [comment]
@dylan-copeland @chldkdtn It turns out many regression tests break. As the snapshot vectors are different, everything including singular values, singular vectors, time steps and the solution are different. By manually read the online stage log files one by one, the runs are all successfully complete, but the results are different from the baseline. In most of the tests, the differences are slight as expected, but there are few tests which yield very big difference.

**Review by dylan-copeland — APPROVED** [review]
This change seems fine, and I am relying on your verification @siuwuncheung that the regression tests had acceptable small changes.

**Pull request merged**
