### PR TITLE
Rom online serial

### PR DESCRIPTION
**Pull request by kevinhkhuynh**
Separate rom-online hyperreduction to online-preprocessing (romhrprep) and online-simulation (romhr) phase.

### CODE REVIEW

**Comment by kevinhkhuynh** [comment]
Every test passes except for 

sedov-blast/sedov-blast-time-window-rhsbasis-parameter-variation-interpolate (No seg-fault, but the romS norm suddenly goes to nan one step after the first window change. I'm not too sure why this one is failing since it looks identical to saveLoadOffset and useInitial, but those pass)
sedov-blast/sedov-blast-time-window-rhsbasis-parameter-variation-previous
sedov-blast/sedov-blast-time-window-rhsbasis-parameter-variation-numsamp (also uses previous, so fixing the test before will fix this test too)

To run the regression tests, "sbatch runRegressionTests.sh -x" must be used. -x allows us to use the new test that separates online into two commands and compare with the output of the singular online command on the master branch.

**Comment by kevinhkhuynh** [comment]
Any variable/function name can be changed since I am still unfamiliar with Laghos and I'm sure the names can be improved. There are 4 new ROM_Basis functions.

During romhrprep (online-preprocessing)
writeSP: write the SP variables to files
computeWindowProjection: precompute the B{i}^T*B{i-1} matrix, which is then saved when writeSP is called. 0th window does not call this.

During romhr (online-simulation)
readSP: read the SP variables from files
ProjectFromPreviousWindow: do the B{i}^T*B{i-1} multiplication on romS using the saved values from computeWindowProjection. 0th window does not call this.

**Comment by kevinhkhuynh** [comment]
@dylan-copeland It is cleaned.

**Comment by dylan-copeland** [comment]
Note that for some Sedov regression tests, `-rostype previous` is replaced by `-rostype interpolate`, and one `previous` test was completely removed. In order to run regression tests for this branch, it is therefore necessary to use as the baseline a branch with the same changes to the regression tests. For this purpose, the branch rom-noprev has been created temporarily in the repo. To use	it as the baseline, change `rom` to `rom-noprev` on line 207 of runRegressionTests.sh. Then all the regression tests should pass.

**Comment by chldkdtn** [comment]
@dylan-copeland, looks like this PR needs to be merged from the rom branch to resolve the conflict in rom/laghos_rom.hpp file.

**Review by dylan-copeland — APPROVED** [review]

**Comment by dylan-copeland** [comment]
This is ready for review. Please note the comment above for regression testing against branch `rom-noprev` (tests will fail if you try to test against branch `rom`).

**Review by siuwuncheung — APPROVED** [review]

**Review by chldkdtn — APPROVED** [review]

**Pull request merged**
