### PR TITLE
Updating the 3D triple point example

### PR DESCRIPTION
**Pull request by kmittal2**
Updating the meshes and initial conditions used for the triple point problem. Below is a snapshot of the specific internal energy at simulation time t=5.
<a href="https://user-images.githubusercontent.com/12035999/91890938-0d676580-ec45-11ea-9ff4-96199b57d013.png"></a>

### CODE REVIEW

**Comment by vladotomov** [comment]
- [x] Update numbers in README.
- [x] Update picture and sample run in the README.
- [x] Update regression tests.

**Review by tzanio — APPROVED** [review]

**Comment by tzanio** [comment]
Unrelated to this PR, but can we remove some of the Laghos branches?

There are 40 of them in https://github.com/CEED/Laghos/branches/all, and I suspect most are no longer relevant.

**Comment by vladotomov** [comment]
> There are 40 of them in https://github.com/CEED/Laghos/branches/all, and I suspect most are no longer relevant.

Deleted 2, and there are 2-3 others that we need. There are 27 `rom` branches and some old GPU-related branches.

**Review by vladotomov — APPROVED** [review]

**Comment by vladotomov** [comment]
@camierjs this seems ready.

**Comment by tzanio** [comment]
> > There are 40 of them in https://github.com/CEED/Laghos/branches/all, and I suspect most are no longer relevant.
> 
> Deleted 2, and there are 2-3 others that we need. There are 27 `rom` branches and some old GPU-related branches.

@chldkdtn, do you need all the `rom` branches?

**Comment by chldkdtn** [comment]
@tzanio We will clean rom branches as much as possible. Thank you for the note.

**Comment by tzanio** [comment]
> @tzanio We will clean rom branches as much as possible. Thank you for the note.

Thanks @chldkdtn

**Review by camierjs — APPROVED** [review]

**Pull request merged**
