### PR TITLE
Refactoring merge phase

### PR DESCRIPTION
**Pull request by siuwuncheung**

### CODE REVIEW

**Comment by kevinhkhuynh** [comment]
Should this be merged to rom or rom_shift-sv?

**Comment by siuwuncheung** [comment]
> Should this be merged to rom or rom_shift-sv?

Both makes sense to me. Maybe we merge to rom-shift-sv.

**Review by kevinhkhuynh — APPROVED** [review]

**Comment by kevinhkhuynh** [comment]
I think we can just merge to rom-shift-sv and do the review there.

**Comment by chldkdtn** [comment]
> I think we can just merge to rom-shift-sv and do the review there.

This sounds good to me.

**Pull request merged**
