### PR TITLE
Sample mesh VisIt visualization

### PR DESCRIPTION
**Pull request by dylan-copeland**
This PR is paired with libROM PR 81 https://github.com/LLNL/libROM/pull/81

The sample elements are visualized globally on the full-order mesh, for each window, in `run/sampleElems_{N}_000000` where N is the time window index. The field `Sample Elements` is 1 on sample elements, 0 elsewhere. It is tested in serial and parallel, for the Sedov test.

It may be more convenient to add each time window's sample mesh visualization to a database, where time window index corresponds to VisIt timestep, so that VisIt animations can be made, stepping through all the time windows. That could be done by passing the VisIt DC to `CreateSampleMesh` rather than the filename.

Note that VisIt may display a uniformly refined mesh, incorrectly, as in the plot below (mesh has 8^3 elements, but VisIt shows 16^3).

sampleMesh

### CODE REVIEW

**Comment by siuwuncheung** [comment]
Thanks @dylan-copeland . This is wonderful! At the moment I will need it in serial ROMs. In the long term it will be useful in many scenarios.

**Review by siuwuncheung — APPROVED** [review]

**Comment by dylan-copeland** [comment]
Here are some ParaView examples. We can highlight sampled vertices, edges, faces, and interior element DOFs. They can be displayed separately or together. In 2D, it is possible to see them together, but in 3D it becomes more difficult to get a clear visualization. Animations can be made, to loop over the time windows.
gresho 0001
sedovVerts
sedovEdges

**Comment by chldkdtn** [comment]
This is nice. For the vertices, can it be visualized with the underlying mesh?

**Comment by dylan-copeland** [comment]
> This is nice. For the vertices, can it be visualized with the underlying mesh?

Yes, it can be. In 2D I have gotten clear visualizations with vertices and edges highlighted. In 3D it becomes difficult to see everything together, but it can be done.

**Review by chldkdtn — APPROVED** [review]

**Pull request merged**
