### PR TITLE
Rom remove sample mesh file

### PR DESCRIPTION
**Pull request by kevinhkhuynh**
Tied to https://github.com/LLNL/libROM/pull/64

### CODE REVIEW

**Comment by kevinhkhuynh** [comment]
If you would like to test against the baseline branch:

In setup.sh, add 'git checkout feature/introduce_mfem' after 'cd libROM'

Then, the following command must be run in the dependencies directory (just until the merge is complete):

ln -s libROM/dependencies/mfem mfem

To test with user branch:

Use -t option.

**Comment by kevinhkhuynh** [comment]
Tests pass.

**Review by dylan-copeland — APPROVED** [review]
Some of the stuff in `laghos_utils.cpp` could now go into libROM, e.g. `PrintParGridFunction`, `PrintNormsOfParGridFunctions`. However, there are some issues	that need to be resolved with the norm function, so we can do that in a future PR.

**Comment by kevinhkhuynh** [comment]
> 
> 
> Some of the stuff in `laghos_utils.cpp` could now go into libROM, e.g. `PrintParGridFunction`, `PrintNormsOfParGridFunctions`. However, there are some issues that need to be resolved with the norm function, so we can do that in a future PR.

Sounds good to me.

**Review by chldkdtn — APPROVED** [review]

**Review by siuwuncheung — APPROVED** [review]

**Comment by chldkdtn** [comment]
@kevinhkhuynh This needs to be merged

**Pull request merged**
