### PR TITLE
[OCCA] Added initial OCCA 1.0 port

### PR DESCRIPTION
**Pull request by dmed256**
Still missing fixing convergence and adding verification section

TODO:
- [x] Update `occa/README.md`

### CODE REVIEW

**Review by camierjs — CHANGES_REQUESTED** [review]
- In MFEM/occa-dev, I had to do the `make cache-kernels`
- In Laghos/occa, MFEM_DIR has to be set `make MFEM_DIR=/.../mfem/occa`
- In UpdateQuadratureData2D, I have a warning: `iteration 16 invokes undefined behavior`
- Verification of Results: I have some difficulties finding a run that converges

**Comment by dmed256** [comment]
@camierjs 
- Removed manual kernel caching in OCCA in favor of setting a library path
```c++
occa::io::addLibraryPath("laghos", "./kernels");
```
- There is no `mfem/occa` directory, it should be `mfem/` with a branch checked out (unless we change the installation instructions to install occa-dev to `mfem-occa/` or something)
- Just pushed fixes

Differences include:
- Calculation of `stressJinvT`
- Logic to compute `GetTimeStepEstimate`

I'll keep investigating

**Comment by camierjs** [comment]
Besides converence, it sounds good!
Thanks David

**Review by camierjs — APPROVED** [review]

**Review by tzanio — APPROVED** [review]

**Comment by tzanio** [comment]
Approved modulus TODO items in the PR description.

**Comment by tzanio** [comment]
@vladotomov: this is ready for merging, can you take a look?

**Review by vladotomov — APPROVED** [review]

**Pull request merged**
