### PR TITLE
Refactor online ROM code

### PR DESCRIPTION
**Pull request by dylan-copeland**
This PR refactors the online stage of the ROM simulation, so that the online setup is done before the timestepping, for all time windows if applicable. Before this PR, the `ROM_Basis` and `ROM_Operator` for each window were constructed during the time-stepping, when time windows changed. Now, this is moved to the pre-processing before the time-stepping. The online setup and online simulation are still done in the same run (`-online`), to avoid writing and reading all the data members of `ROM_Basis` and `ROM_Operator` to and from files. Although the `-online` run still contains both setup and simulation, the timings are clearer now, with pre-processing timing including all the construction rather than the simulation timing, which should make the online simulation run time smaller.

The `restore` phase is not refactored.

For problems with sufficiently many spatial DOFs or timesteps, constructing all `ROM_Basis` and `ROM_Operator` instances for all time windows should cause memory failures. If this happens, we can easily implement the option to use the old version where the construction is done for one window at a time (this will not require significant code changes like the current refactoring).

### CODE REVIEW

**Review by kevinhkhuynh — APPROVED** [review]
Looks good to me.

**Review by siuwuncheung — APPROVED** [review]

**Review by chldkdtn — APPROVED** [review]

**Comment by chldkdtn** [comment]
LGTM

**Comment by dylan-copeland** [comment]
@kevinhkhuynh It looks like @chldkdtn and I still do not have LGTM power. Could you please do LGTM?

**Comment by kevinhkhuynh** [comment]
LGTM

**Comment by kevinhkhuynh** [comment]
LGTM

**Comment by kevinhkhuynh** [comment]
LGTM

**Pull request merged**
