### PR TITLE
Space-time ROM

### PR DESCRIPTION
**Pull request by dylan-copeland**
Implementing space-time ROM, using branch `space-time-sampling` of libROM. Below are some tests with good accuracy or speed-up. In addition to the listed sample runs, coll_lspg and gnat_lspg can be interchanged to specify collocation LSPG or GNAT-LSPG, respectively.

This is really a work in progress, so the code is far from completion, but the idea is to merge now to prevent very large changes and conflicts. The disadvantage is that it introduces somewhat messy, incomplete code, but only temporarily. There are many TODOs documenting issues with the current version. I suppose the goal in reviewing this PR is to make sure it does not break anything other than the space-time solver, not to ensure that the code is ready (cleary it is not).

This initial version assumes one temporal basis vector per spatial basis vector, which should be generalized in the future. Currently, FOM data is constructed in the online phase for space-time, which should be avoided in the future. Also, the restore phase should be supported for space-time.

The libROM function `SpaceTimeProduct` is not used and perhaps can be removed. It was originally used for the Galerkin formulation of space-time.

The Galerkin case does not work, seemingly for theoretical reasons, and perhaps should be removed.

SNS will be supported in the future.

The parallel case was working in a previous version, but now the online phase needs to be serial. Because of that complication which has not been resolved yet, the parallel case is not supported currently.

Regression tests are added for space-time. All tests except the new ones pass, as expected.

A notable change that will affect Laghos ROM testing in general is in `basisComparator.cpp`, where I changed the l2 norm calculation for the difference of basis vectors. First, I corrected it to be the l2 norm (was `sum_i sqrt(sum_j d_ij^2))` and should have been `sqrt( sum_i sum_j d_ij^2)`), and reduced the number of `MPI_Reduce` calls. Second, I introduced scaling of each basis vector l2 norm by the corresponding singular value, so that basis vectors corresponding to small singular values receive less weight (for the smallest, essentially no weight, and there is no comparison). In conjunction with this change, the tolerance was reduced from 1e-7 to 1e-14. This was necessary for this PR to pass regression tests, implying that there were differences (relative 1e-6) for the basis vectors corresponding to the smallest singular values. While this is not a significant difference, and could have passed just by raising the tolerance, I think it makes more sense in general to do the scaling, but I am open to other suggestions. It seems likely that small changes in the code (Laghos or libROM) could have significant effects on the most insignificant basis vectors. The only mysteries remaining are (i) why this never occurred before, and (ii) why this PR had an issue. This PR should not have any effect on bases (in this case `basisFv0` for taylor-green-offline-parallel), so I still don't understand why there was a 1e-6 difference in some basis vectors whereas most bases have exactly 0 difference in testing. I can only guess that some reordering of code or operations caused round-off level error that becomes significant in some singular vectors.

Sedov test:
srun -n 1 -p pdebug laghos -m data/cube01_hex.mesh -pt 211 -tf 0.1 -offline -writesol -romsvds -romst coll_lspg -no-romgs -no-romoffset
srun -n 1 -p pdebug laghos -m data/cube01_hex.mesh -pt 211 -tf 0.1 -online -romst coll_lspg -romhrprep -rdimx 6 -rdimv 46 -rdime 15 -rdimfv 50 -rdimfe 30 -ntsamv 1 -ntsame 1 -sfacv 2 -sface 2 -soldiff -no-romgs -no-romoffset
srun -n 1 -p pdebug laghos -m data/cube01_hex.mesh -pt 211 -tf 0.1 -online -romst coll_lspg -romhr -rdimx 6 -rdimv 46 -rdime 15 -rdimfv 50 -rdimfe 30 -ntsamv 1 -ntsame 1 -sfacv 2 -sface 2 -soldiff -no-romgs -no-romoffset

Triple-point test:
srun -n 1 -p pdebug laghos -p 3 -m data/box01_hex.mesh -rs 1 -tf 0.1 -cfl 0.05 -offline -writesol -romsvds -romst coll_lspg -no-romgs -no-romoffset
srun -n 1 -p pdebug laghos -p 3 -m data/box01_hex.mesh -rs 1 -tf 0.1 -cfl 0.05 -online -romst coll_lspg -romhrprep -rdimx 2 -rdimv 5 -rdime 4 -rdimfv 7 -rdimfe 6 -ntsamv 1 -ntsame 1 -sfacv 2 -sface 2 -soldiff -no-romgs -no-romoffset
srun -n 1 -p pdebug laghos -p 3 -m data/box01_hex.mesh -rs 1 -tf 0.1 -cfl 0.05 -online -romst coll_lspg -romhr -rdimx 2 -rdimv 5 -rdime 4 -rdimfv 7 -rdimfe 6 -ntsamv 1 -ntsame 1 -sfacv 2 -sface 2 -soldiff -no-romgs -no-romoffset

Taylor-Green test (nonzero initial V requires full sampling):
srun -n 1 -p pdebug laghos -m data/cube01_hex.mesh -p 0 -rs 1 -iv -cfl 0.5 -tf 0.07 -offline -writesol -romsvds -romst coll_lspg -no-romgs -no-romoffset
srun -n 1 -p pdebug laghos -m data/cube01_hex.mesh -p 0 -rs 1 -iv -cfl 0.5 -tf 0.07 -online -romst coll_lspg -romhrprep -rdimx 10 -rdimv 10 -rdime 10 -rdimfv 15 -rdimfe 15 -ntsamv 10 -ntsame 10 -sfacv 10 -sface 10 -soldiff -no-romgs -no-romoffset
srun -n 1 -p pdebug laghos -m data/cube01_hex.mesh -p 0 -rs 1 -iv -cfl 0.5 -tf 0.07 -online -romst coll_lspg -romhr -rdimx 10 -rdimv 10 -rdime 10 -rdimfv 15 -rdimfe 15 -ntsamv 10 -ntsame 10 -sfacv 10 -sface 10 -soldiff -no-romgs -no-romoffset

### CODE REVIEW

**Comment by chldkdtn** [comment]
@kevinhkhuynh Can you make this PR so that the laghos executable can be run in a folder other than laghos/rom? I know it is already implemented in greedy branch. But it seems that we will merge this PR first.

**Comment by kevinhkhuynh** [comment]
> 
> 
> @kevinhkhuynh Can you make this PR so that the laghos executable can be run in a folder other than laghos/rom? I know it is already implemented in greedy branch. But it seems that we will merge this PR first.

Done.

**Comment by chldkdtn** [comment]
I think that the both ways of the l2 norm computation, i.e., (i)  sum_i sqrt(sum_j d_ij^2) and (ii) sqrt( sum_i sum_j d_ij^2)), make sense. The first one is comparing the sum of the l2 norm of each basis vector difference and the second one is comparing the Frobenius norm of the whole basis difference, right?

**Comment by dylan-copeland** [comment]
> I think that the both ways of the l2 norm computation, i.e., (i) sum_i sqrt(sum_j d_ij^2) and (ii) sqrt( sum_i sum_j d_ij^2)), make sense. The first one is comparing the sum of the l2 norm of each basis vector difference and the second one is comparing the Frobenius norm of the whole basis difference, right?

Yes, I agree both ways should be fine, and it may not be necessary to make this change. The main change I needed was the scaling of the basis vectors in the difference computation.

**Review by chldkdtn — APPROVED** [review]

**Review by siuwuncheung — APPROVED** [review]

**Review by kevinhkhuynh — APPROVED** [review]

**Pull request merged**
