### PR TITLE
Change default ROM options

### PR DESCRIPTION
**Pull request by siuwuncheung**
This is a small PR to change the default values several frequently used ROM options in order to shorten the command lines. 

1. The `restore` phase is added to the parametric ROM regression tests. 
2. The default value of `romOptions.useOffset` becomes true. The tag `-romos` is added to all regression tests, in order to compare the results with the current `rom` branch. 
3. The default value of `romOptions.staticSVD` becomes true. The tag `-no-romsvds` is added to the incremental SVD regression tests and `-romsvds` is added to all other regression tests, in order to compare the results with the current `rom` branch. 
4. In writing the time window parameter file, the filename changes from `twpTemp.csv` to the variable `twpfile`, which is specified using the tag `-twp` originally exists in `laghos` and newly added to `merge`. The option `-twp twpTemp.csv` are added to the offline phase of all time windowing regression tests, in order to compare the results with the current `rom` branch. However, since it is newly added to `merge`, the time windowing parametric ROM regression tests are supposed to fail.
5. The default value of `romOptions.GramSchmidt` becomes true. 
6. The option `RHSbasis` is removed. The tags `-romsrhs` and `-rhs` are removed.

### CODE REVIEW

**Comment by chldkdtn** [comment]
testing regression tests for this PR is crucial.

**Comment by siuwuncheung** [comment]
> testing regression tests for this PR is crucial.

PR #138 is now merged. I will have a careful check on the regression test results of this PR.

**Comment by kevinhkhuynh** [comment]
If you change the base branch to some random branch and change it back to rom, all of the commits relating to PR #138 should disappear.

**Comment by siuwuncheung** [comment]
> If you change the base branch to some random branch and change it back to rom, all of the commits relating to PR #138 should disappear.

Seems it does not work. Maybe it is because I used squash and merge for PR #138

**Comment by kevinhkhuynh** [comment]
LGTM

**Review by dylan-copeland — APPROVED** [review]
These changes look fine to me. I did not run the regression tests, as I trust @siuwuncheung and @kevinhkhuynh are verifying they pass. It seems the `dummy` variables are necessary only for backward-compatibility in testing, and they could be removed in a subsequent PR or immediately before merging this branch (after tests are verified to pass).

**Comment by kevinhkhuynh** [comment]
LGTM

**Comment by kevinhkhuynh** [comment]
LGTM

**Comment by siuwuncheung** [comment]
> These changes look fine to me. I did not run the regression tests, as I trust @siuwuncheung and @kevinhkhuynh are verifying they pass. It seems the `dummy` variables are necessary only for backward-compatibility in testing, and they could be removed in a subsequent PR or immediately before merging this branch (after tests are verified to pass).

@dylan-copeland Thanks for your review. Yes the `dummy` variables are solely for backward compatibility. Once @kevinhkhuynh verifies the regression tests are passing, two more commits breaking lots of tests will be pushed: one for removing the `dummy` variables and tags in regression test scripts, and the other one for setting `GramSchmidt = true` as default while fixing a minor bug with the SNS case.

**Comment by kevinhkhuynh** [comment]
@siuwuncheung Tests currently passing.

**Review by chldkdtn — APPROVED** [review]

**Comment by siuwuncheung** [comment]
@kevinhkhuynh The new changes are now pushed. I will merge after your approval.

**Review by kevinhkhuynh — APPROVED** [review]

**Pull request merged**
